// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STUDENT_API;

#nullable disable

namespace STUDENT_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231116130338_Elina-Migracija")]
    partial class ElinaMigracija
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("STUDENT_API.Models.Profesor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plata")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("STUDENT_API.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojIndexa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumUpisa")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrzavaRodjenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradRodjenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50d7b5f7-8ca0-4425-8881-03fa18dcd5fc"),
                            BrojIndexa = "036011/20",
                            DatumUpisa = new DateTime(2021, 3, 16, 13, 3, 38, 486, DateTimeKind.Utc).AddTicks(9712),
                            DrzavaRodjenja = "Srbija",
                            GradRodjenja = "Novi Pazar",
                            Ime = "Adnan",
                            Prezime = "Crnovrsanin"
                        },
                        new
                        {
                            Id = new Guid("850ba02c-5af9-4c9b-a9f2-0f903bec689b"),
                            BrojIndexa = "036035/21",
                            DatumUpisa = new DateTime(2022, 3, 16, 13, 3, 38, 486, DateTimeKind.Utc).AddTicks(9727),
                            DrzavaRodjenja = "Srbija",
                            GradRodjenja = "Novi Pazar",
                            Ime = "Mirnesa",
                            Prezime = "Crnovrsanin"
                        },
                        new
                        {
                            Id = new Guid("a91ef508-098c-4d81-8aba-c2f904004238"),
                            BrojIndexa = "058441/21",
                            DatumUpisa = new DateTime(2022, 3, 16, 13, 3, 38, 486, DateTimeKind.Utc).AddTicks(9729),
                            DrzavaRodjenja = "Srbija",
                            GradRodjenja = "Novi Sad",
                            Ime = "Amina",
                            Prezime = "Hasanovic"
                        },
                        new
                        {
                            Id = new Guid("05d9f29c-dcf5-4034-adf6-3ae0aba0859e"),
                            BrojIndexa = "038511/20",
                            DatumUpisa = new DateTime(2021, 3, 16, 13, 3, 38, 486, DateTimeKind.Utc).AddTicks(9731),
                            DrzavaRodjenja = "Srbija",
                            GradRodjenja = "Tutin",
                            Ime = "Hasim",
                            Prezime = "Tutic"
                        },
                        new
                        {
                            Id = new Guid("d74fa983-6276-4e07-8adb-cfccca241ff5"),
                            BrojIndexa = "088711/20",
                            DatumUpisa = new DateTime(2021, 3, 16, 13, 3, 38, 486, DateTimeKind.Utc).AddTicks(9734),
                            DrzavaRodjenja = "Srbija",
                            GradRodjenja = "Novi Pazar",
                            Ime = "Hamza",
                            Prezime = "Delic"
                        },
                        new
                        {
                            Id = new Guid("33d84c84-7a0c-4e5f-9816-3513f354dd16"),
                            BrojIndexa = "088711/20",
                            DatumUpisa = new DateTime(2021, 3, 16, 13, 3, 38, 486, DateTimeKind.Utc).AddTicks(9738),
                            DrzavaRodjenja = "ASajd",
                            GradRodjenja = "Novi Sad",
                            Ime = "ne znam",
                            Prezime = "Mirbejnd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
