// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STUDENT_API;

#nullable disable

namespace STUDENT_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230615232456_dodajemoStudente")]
    partial class dodajemoStudente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("STUDENT_API.Models.Profesor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Plata")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("STUDENT_API.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrojIndexa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumUpisa")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrzavaRodjenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradRodjenja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83c1640b-0c70-4f39-b7d1-3356976cb44a"),
                            BrojIndexa = "036011/20",
                            DatumUpisa = new DateTime(2020, 10, 15, 23, 24, 56, 444, DateTimeKind.Utc).AddTicks(2772),
                            DrzavaRodjenja = "Srbija",
                            GradRodjenja = "Novi Pazar",
                            Ime = "Adnan",
                            Prezime = "Crnovrsanin"
                        },
                        new
                        {
                            Id = new Guid("2e5fe57f-d68d-4c69-b238-f1e9a64a6232"),
                            BrojIndexa = "036035/21",
                            DatumUpisa = new DateTime(2021, 10, 15, 23, 24, 56, 444, DateTimeKind.Utc).AddTicks(2789),
                            DrzavaRodjenja = "Srbija",
                            GradRodjenja = "Novi Pazar",
                            Ime = "Mirnesa",
                            Prezime = "Crnovrsanin"
                        },
                        new
                        {
                            Id = new Guid("5d337cec-b283-4563-ad16-9a86f9a6729f"),
                            BrojIndexa = "058441/21",
                            DatumUpisa = new DateTime(2021, 10, 15, 23, 24, 56, 444, DateTimeKind.Utc).AddTicks(2792),
                            DrzavaRodjenja = "Srbija",
                            GradRodjenja = "Novi Sad",
                            Ime = "Amina",
                            Prezime = "Hasanovic"
                        },
                        new
                        {
                            Id = new Guid("001d6d22-a6cd-4e75-a39f-f22587454add"),
                            BrojIndexa = "038511/20",
                            DatumUpisa = new DateTime(2020, 10, 15, 23, 24, 56, 444, DateTimeKind.Utc).AddTicks(2795),
                            DrzavaRodjenja = "Srbija",
                            GradRodjenja = "Tutin",
                            Ime = "Hasim",
                            Prezime = "Tutic"
                        },
                        new
                        {
                            Id = new Guid("ec97391d-6aac-48dd-b652-846562f68418"),
                            BrojIndexa = "088711/20",
                            DatumUpisa = new DateTime(2020, 10, 15, 23, 24, 56, 444, DateTimeKind.Utc).AddTicks(2798),
                            DrzavaRodjenja = "Srbija",
                            GradRodjenja = "Novi Pazar",
                            Ime = "Hamza",
                            Prezime = "Delic"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
